
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: pms_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5544:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
